[project]
name = "financial-tracker"
version = "0.1.0"
description = "Luca Marchetti's Financial Tracker"
readme = "README.md"
requires-python = "==3.12.*"
authors = [{ name = "Luca Marchetti", email = "lucamarche02@gmail.com" }]
dependencies = [
  "flet>=0.85.0",
  "flet-charts>=0.85.0",
  "flet-datatable2>=0.85.0",
  "matplotlib>=3.11.0",
  "numpy>=2.4.6",
  "pydantic>=2.13.4",
  "pytest>=9.0.3",
]

[dependency-groups]
dev = [
  "flet-cli>=0.85.0",
  "flet-desktop>=0.85.0",
  "flet-web>=0.85.0",
  "ruff>=0.15.12",
]

[tool.flet]
org = "com.lucamarchetti"
product = "Financial Tracker"
company = "Luca Marchetti"
copyright = "Copyright (C) 2026 by Luca Marchetti"
artifact = "Financial Tracker"
bundle_id = "com.lucamarchetti.financial-tracker"

[tool.flet.app]
path = "src"

[tool.flet.macos.info]
CFBundleDisplayName = "Financial Tracker"

[tool.pytest.ini_options]
minversion = "9.0"
addopts = "-s -vv -x"
testpaths = ["tests"]
pythonpath = "src"
